[2025-04-16 15:40:18] ERROR: Another instance is running
